/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FcyThrz0nem
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { ChatPanel } from "./chat-panel"
import { DocumentSection } from "./document-section"

export function ChatPageComponent({user, getToken, logout}) {
  return (
    <div className="grid grid-cols-2 h-screen w-full bg-background overflow-hidden">
      <ChatPanel user={user} getToken={getToken} logout={logout} />
      <DocumentSection />
    </div>
  )
}