/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IebEHdR5vmu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "./ui/button"

export function HomeComponent({login}) {
  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-[url('/pangolin-background.jpg')] bg-cover bg-center">
      <div className="max-w-md px-4 py-12 sm:px-6 lg:px-8">
        <div className="space-y-4 text-center">
          <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm font-medium text-primary">
            Welcome to Pango Bank
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-[#9b59b6] sm:text-5xl">Banking for Pangolins</h1>
          <p className="text-muted-foreground">
            Secure and convenient banking services tailored for the pangolin community.
          </p>
          <Button
            className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            onClick={login}
          >
            Login
          </Button>
        </div>
      </div>
    </div>
  )
}
